# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-20 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppResource',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resource.Resource')),
                ('image_name', models.CharField(max_length=200)),
                ('command', models.CharField(blank=True, max_length=400, null=True)),
                ('required_resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='required_by_apps', to='resource.DictResource')),
            ],
            options={
                'abstract': False,
            },
            bases=('resource.resource',),
        ),
        migrations.CreateModel(
            name='MountedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mount_path', models.CharField(max_length=300)),
                ('file', models.FileField(upload_to='mounted_files/')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='application.AppResource')),
            ],
        ),
    ]
